// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACEJK5RDG0dIbjrFk3OrLFPeUXLl7_HU8',
    appId: '1:724661990861:web:c01dad71800c2d7b1c8084',
    messagingSenderId: '724661990861',
    projectId: 'atc-international',
    authDomain: 'atc-international.firebaseapp.com',
    storageBucket: 'atc-international.appspot.com',
    measurementId: 'G-4PKQQ4NEKZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQNi1UcjqGcZEh6z8H6-rPKd2johNjL5k',
    appId: '1:724661990861:android:567777acbc8c94a21c8084',
    messagingSenderId: '724661990861',
    projectId: 'atc-international',
    storageBucket: 'atc-international.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYR0BIBA-rzL8AmwCE5Adb1lxX_IADLk0',
    appId: '1:724661990861:ios:35416c854b4411211c8084',
    messagingSenderId: '724661990861',
    projectId: 'atc-international',
    storageBucket: 'atc-international.appspot.com',
    androidClientId: '724661990861-kt6uiv8jrti1b5nfaoh78hkjbl6l1f7m.apps.googleusercontent.com',
    iosClientId: '724661990861-rom81mm54jfli6btj4vbng2homf66unt.apps.googleusercontent.com',
    iosBundleId: 'com.example.atcInternational',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYR0BIBA-rzL8AmwCE5Adb1lxX_IADLk0',
    appId: '1:724661990861:ios:35416c854b4411211c8084',
    messagingSenderId: '724661990861',
    projectId: 'atc-international',
    storageBucket: 'atc-international.appspot.com',
    androidClientId: '724661990861-kt6uiv8jrti1b5nfaoh78hkjbl6l1f7m.apps.googleusercontent.com',
    iosClientId: '724661990861-rom81mm54jfli6btj4vbng2homf66unt.apps.googleusercontent.com',
    iosBundleId: 'com.example.atcInternational',
  );
}
